### ISSUE TITLE
long multiplication/division results incorrect

### ISSUE THREAD

**Issue by mcvde** [mburkley/tms9900-gcc#31]
I've been getting around to adding binary file support with fwrite/freed and that's led me to starting to use long types a bit more. I have that mostly working, but in writing the unit test where I try to randomize seeks within the file, I decided to show percent complete, since the test will run for quite some time.

In calculating the percent complete, I have a long, k, for the current iteration and long, c, for the total number of iterations. I noticed while watching the percents display that the number would go backwards!

Larger file manipulation also fails but very likely for this division reason as I calculate blocks and offsets there with long types.

I apologize that the code is rather peppered with type casts to try to force to long types, but to no avail.

I also noticed that the compiler call was divsi3 which is for integers rather than the one for long.
.text          0x000000000000c694       0x10 /opt/tms9900/gcc-4.4.0/lib/gcc/tms9900/4.4.0/libgcc.a(_divsi3.o)
                0x000000000000c694                __divsi3
 .text          0x000000000000c6a4       0x14 /opt/tms9900/gcc-4.4.0/lib/gcc/tms9900/4.4.0/libgcc.a(_modsi3.o)
                0x000000000000c6a4                __modsi3
 .text          0x000000000000c6b8       0x3a /opt/tms9900/gcc-4.4.0/lib/gcc/tms9900/4.4.0/libgcc.a(_divmod_common.o)
                0x000000000000c6dc                __divmodend
                0x000000000000c6b8                __divmodstart
 .text          0x000000000000c6f2       0x72 /opt/tms9900/gcc-4.4.0/lib/gcc/tms9900/4.4.0/libgcc.a(_udivsi3.o)
                0x000000000000c6f2                __udivmod32
                0x000000000000c6f2                __udivsi3

#include <stdio.h>
#include <conversion.h>

int main (int argc, char *argv[]) {

   long c = 0;
   long k = 0;
   int pct_now;
   int pct_last = 0;

   fputs ("longtest\n", stdout);

   c = 66528;
   for (k = 0; k < 2000; k++) {
      pct_now = (long) ((k * (long) 100) / c);
      fputs (int2str (pct_now), stdout);
      fputs (" ", stdout);
      fputs (ltoa (k), stdout);
      fputs (" ", stdout);
      fputs (ltoa (c), stdout);
      if (pct_now < pct_last) {
         fputs ("\nyikes!", stdout);
      }
      fputs ("\n", stdout);
      pct_last = pct_now;
   }

   return 0;
}

The program output (truncated) is:
<img width="1614" alt="Screenshot 2023-12-22 at 7 30 55 PM" src="https://github.com/mburkley/tms9900-gcc/assets/126357373/e71f3880-b48f-49a3-bb71-18f26468ae54">

**Comment by mburkley** [comment]
Thanks for the report.  In tms9900, an int is 16-bits (HI) and a long is 32-bits (SI).  There is no native 32-bit mul/div so these have to be constructed as either expands or library calls.  I had taken 32-bit defs out of the md file as gcc was emitting its own 16-bit sequences for 32-bit ops like add/sub but it looks like it needs help with mul/div.  I'll see where best to add them, maybe implement in libgcc....

**Comment by mburkley** [comment]
Actually _divs3 is in lib1funcs.asm.  I'll add some more tests for that

**Comment by mcvde** [comment]
I found a decent algorithm on wikipedia and implemented it for signed 32 bit division and modulus. Obviously the compiler calls the wrong method for long division. Anyway, if you need an implementation I can provide this and also quickly make an unsigned version as well. The algorithm is O(n) where n is the # of bits in the type.

**Comment by mburkley** [comment]
Yeah that might be best.  I had a quick look at debugging the existing algo using a spreadsheet.  I've confirmed it's broken but haven't found a way to fix it yet.

**Comment by mcvde** [comment]
Sure, NP. 

I've coded the signed/unsigned long now, but need to write some more unit tests. I've tested the signed decently but only three sets of num/denom on unclass. It'll probably take a few days as I have multiple travel days ahead of me now.

Do the existing methods work correctly for uint/int16 types?

**Comment by mburkley** [comment]
I believe (u)int16 is fine.  These use native methods so are much simpler.  There are some wrappers for signed mul/div/mod though.

**Comment by mcvde** [comment]
Good to know. I’m coming along in the unit tests. I apparently messed up my display method for unsigned long. Will plug along.

**Comment by mcvde** [comment]
My apologies...I had expected to provide these ulong/long div/mod methods and unit tests more quickly. 

I have them integrated into my fwrite/fread/fseek/ftell/rewind methods and unit tests. I've not had any reason for the use of long types until I decided to implement these methods to support binary files. Internally they keep track of the current file read/write position which necessarily must be a long to be able to support reasonable sized files. 

All of this took a fair amount of time as I was debugging what seemed to be a very nasty and quite subtle bug. In the end, though, I found I was bumping up against limitations in the TI file system structure and possibly the DSR supporting hard drives. It/they seem to get angry with longer files that are fragmented. My code works fine on non-fragmented files. The reality is that pretty much every file on a TI-99 at this point is probably a short text file or an EA5 file. I have thought to potentially use this format for executable files, as I dislike the EA5 file naming convention that results in some funky names and strange sort order sometimes, not to mention quickly moves towards the 127 max files in a directory problem. 

All this said, I wanted to make sure, I wasn't handing over to you buggy div/mod methods. I believe these are good to go.

In any case, please find the div/mod methods and unit tests here:
[longtest.c.txt](https://github.com/mburkley/tms9900-gcc/files/13823264/longtest.c.txt)
[longdivmod.c.txt](https://github.com/mburkley/tms9900-gcc/files/13823142/longdivmod.c.txt)
[ulongdivmod.c.txt](https://github.com/mburkley/tms9900-gcc/files/13823143/ulongdivmod.c.txt)

**Comment by mburkley** [comment]
I just commented them out.  Builds fine.  Also I changed __divdi3 to __divsi3 etc.

**Comment by mcvde** [comment]
Sounds good. I'm curious about the name change, not that I care, but just to understand. These are the names my older compiler needed. Do these change for gcc 13.x or some other reason?

**Comment by mburkley** [comment]
Well SI is 32-bit, DI is 64-bit.  These are for 32-bit ops only I think?  Long is often defined as 64-bit but in the patches for GCC 4 and 13 I'm defining long as 32-bit since int is 16-bit.
