### ISSUE TITLE
Segfault with debug turned on

### ISSUE THREAD

**Issue by XZCE** [mburkley/tms9900-gcc#39]
https://github.com/mburkley/tms9900-gcc/blob/88427213e3293d27ff17414b5d158f3dcf1e1679/dev/gcc-4.4.0/gcc/config/tms9900/tms9900.md#L1808-L1833

There's only 2 operands to print in these cases.

Looking good though with the latest changes :)

**Comment by mburkley** [comment]
Thanks, fixed on 1.29 branch

**Comment by XZCE** [comment]
Closing as fixed...

Sheesh, don't be sad on AtariAge about the swpb issue, seems to me you worked out the bool postByteSwap flag which if true means you just need "mov" before it, else you need "movb" without it.  I.E. never make sense to do movb+swpb.
