### ISSUE TITLE
 [bug][OK in branch 1.32] Random behavior in previously working code. Hard/impossible to reproduce. 

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [mburkley/tms9900-gcc#59]
The new changes in this repo have fixed some bugs but also introduced several new bugs that affect all my games except the smallest two. Here I only discuss *new* bugs present in the Chase game:
game description: https://github.com/Fabrizio-Caruso/CROSS-LIB/blob/master/docs/GAMES.md#chase
game source code: https://github.com/Fabrizio-Caruso/CROSS-LIB/blob/master/src/games/chase

The code around this line maybe miscompiled:
https://github.com/Fabrizio-Caruso/CROSS-LIB/blob/master/src/games/chase/level.h#L124

Maybe the problem comes from the function 'initializeCharacter' that is invoked to place the enemies and all other objects in their initial positions and defined their shape.

The visible effect of the new problem(s) is:
1. At each level start-up fewer enemies are spawned (which makes the game impossible because you need to kill all of them)
2. The player character is shown on the top-left corner of the screen. This bug may be produced by the wrong position of the enemies.

![image](https://github.com/user-attachments/assets/b538958a-08a4-4f0b-8e71-148dcb7c3c66)

This is very hard to reproduce or isolate because adding some print commands around line 124 produces random graphical glitches and a different number of enemies is spawned.

I have attached the binaries.

 
[build.zip](https://github.com/user-attachments/files/17235934/build.zip)

**Comment by mburkley** [comment]
Most likely related to rsubihi trying to negate a label.  Fixed in 1.32
