### ISSUE TITLE
[bug][OK in branch 1.32] 19-19=255 with this updated version of GCC for the TI instead of 0

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [mburkley/tms9900-gcc#60]
This is one of the many **new** bugs I am encountering when compiling my games with GCC for TI.
This bug affects my Stinger game:
https://github.com/Fabrizio-Caruso/CROSS-LIB/tree/master/src/games/stinger

This bug is straightforward: 19-19 = 0 but the compiler gives us 255.

The miscompiled code is here:
https://github.com/Fabrizio-Caruso/CROSS-LIB/blob/master/src/games/stinger/main.c#L2465

I have added some prints to see what the values of the variables when compiled with native recent GCC vs this version of GCC for the TI.
The pictures show the value of `spawned_heavy ` with the correct result (i.e., 0) on the native terminal vs the TI99 (i.e., 255).
The fourth value is supposed to be the difference of the second (19) and third value (19).

![image](https://github.com/user-attachments/assets/9fc9d487-925d-4f39-9802-855bcf89acd7)

![image](https://github.com/user-attachments/assets/568e4f01-5a71-40db-a3e4-0e05c71622d3)

The modified code is here:
```
#define spawn_initial_heavy_tanks() \
    heavy_tanks_to_kill = heavy_tanks_on_level[level]-killed_heavy_tanks; \
    \
    if(heavy_tanks_to_kill<max_occupied_columns - spawned_light) \
    { \
        spawned_heavy = heavy_tanks_to_kill;   \
    } \
    else \
    { \
        spawned_heavy = max_occupied_columns - spawned_light; \
    } \
    \
    tank_counter = 0; \
    \
    _XL_PRINTD(0,2,3,heavy_tanks_to_kill); \
    _XL_PRINTD(4,2,3,max_occupied_columns); \
    _XL_PRINTD(8,2,3,spawned_light); \
    _XL_PRINTD(12,2,3,spawned_heavy); \
    _XL_PRINTD(16,2,3,heavy_tanks_on_level[level]); \
    _XL_PRINTD(20,2,3,killed_heavy_tanks); \
    while(tank_counter<spawned_heavy) \
    { \
        _XL_PRINTD(0,4,3,tank_counter); \
        spawn_heavy_tank(); \
        initialize_tank_at_level_restart(); \
    } \
    \
    heavy_tanks_to_spawn = heavy_tanks_to_kill-spawned_heavy;
```

In the attachments you find the EA5 binaries.
[build.zip](https://github.com/user-attachments/files/17236968/build.zip)

**Comment by mburkley** [comment]
This was related to subtract from constant in rsubihi.  Fixed in 1.32
