### ISSUE TITLE
[bug][OK in branch 1.32] Shift operations and addition seem to give wrong result, but this is triggered or affected by PRINT commands

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [mburkley/tms9900-gcc#65]
This isa  bug I do not observe in GCC for TI before any of the changes in this repo. 
It was OK before any work here but it was KO before 1.31/1.32 and in master branch:
- 1.31/1.32: KO
- master: KO
- before master: OK

I see this bug with `-O2` and `-Os`. I think it also occurs with `-O1` (because I see it in one of my games) but this very specific example is "fixed" by `-O1` probably by some lucky peep-hole or other optimization.

I provide a minimal example that can be compiled with both a native compiler (e.g., GCC), as well as with GCC for the TI + libti99.
The bug may not be just in arithmetic operations because removing the PRINT before and/or after, changes the result and may even fix the result.

The result should always be the same, i.e., `(1<<4)+(1<<8)=16+256=272` but GCC for TI gives us `308`.

```
#if defined(__TI99__)
    #include <conio.h>
    #include <vdp.h>
    #define uint8_t unsigned char
    #define uint16_t unsigned short
    #define PRINT(x,y,str) \
    do \
    { \
        gotoxy(x,y); \
        cprintf(str); \
    } while(0)
    #define PRINTD(x,y,val) \
    do \
    { \
        gotoxy(x,y); \
        cprintf("%d",val); \
    } while(0)
#else
    #include <stdint.h>
    #include <stdio.h>
    #define PRINT(x,y,str) \
    do \
    { \
        printf(str); \
    } while(0)
    #define PRINTD(x,y,val) \
    do \
    { \
        printf("%d",val); \
    } while(0)
#endif

unsigned char word[5] = {0x1, 0x1, 0x1, 0x1, 0x1};

uint16_t compress_bottom_word()
{    
    return (((uint16_t)word[3])<<4)+(((uint16_t)word[2])<<8);
}

int main(void)
{        
    uint16_t compressed_word;
    #if defined(__TI99__)
        set_graphics(VDP_SPR_16x16);                        // set video mode
        vdpmemset(gImage, 32, 768);                         // clear screen
        VDP_SET_REGISTER(VDP_REG_COL, COLOR_BLACK);      // set screen color
    #endif
    PRINT(0,0,"START\n");
    compressed_word = compress_bottom_word();
    PRINTD(0,1,compressed_word);
    PRINT(0,2,"\n");
    while(1){};
    return 0;
}
```

I have attached the EA5 binary (compiled with `-Os -fno-peephole2 -fno-function-cse -fno-builtin`) that shows the wrong result:

[XTI99TESTE1.zip](https://github.com/user-attachments/files/17297170/XTI99TESTE1.zip)

P.S.:
I observe this behavior in one of my games (Verbix: https://github.com/Fabrizio-Caruso/CROSS-LIB/tree/master/src/games/verbix) which was OK before the new changes by @mburkley

**Comment by mburkley** [comment]
Shifting a byte was leaving random data in the low order byte of a word - fixed in 1.32
