### ISSUE TITLE
[bug][ok now in latest changes in branch 1.32] cprintf from libti99 fails to print if we do 2*i before but works fine with (i<<1)

### ISSUE THREAD

**Issue by Fabrizio-Caruso** [mburkley/tms9900-gcc#66]
This bug is old and seems to appear only with `-Os` and `-O2`. Not with `-O1`.
Problem: cprintf from libti99 does no print the text if we perform `2*i` but surprisingly it works if we do` (i<<1)` or if we remove the prototype for the function `loc `(implemented in `loc.c`).

The bug occurs when compiling two files (`main.c` and `loc.c`) found in the attachment.
Tested compilation parameters that produce the bug are ` -O2 -fno-peephole2 -fno-function-cse -fno-builtin` and `-Os -fno-peephole2 -fno-function-cse -fno-builtin`.

The bug may not occur if we do other things to the code such inverting `DRAW `and `PRINT `or adding an extra `PRINT `after the `PRINT` or if we replace`images[NUMBER_OF_STRINGS-i]` with a constant value. It looks unpredictable to me.

Expected behavior:
![image](https://github.com/user-attachments/assets/38c88172-e471-4ae8-96ba-7d720018a513)

Bug:
![image](https://github.com/user-attachments/assets/298f13fd-7540-430d-b488-a7157a12b6e3)

`main.c `

```
#include <conio.h>
#define uint8_t unsigned char
#define uint16_t unsigned int

uint16_t loc(uint8_t x, uint8_t y);

#define PRINT(x,y,str) \
do \
{ \
    gotoxy((x),(y)); \
    cprintf(str); \
} while(0)

#define NUMBER_OF_STRINGS 5
#define MAX_STRING_SIZE (6+1)

static const uint8_t images[] = {
    0, 
    0, 
    0, 
    0, 
    0, 
    0, 
    0, 
    0, 
    0, 
    0, 
    0, 
    0, 
    };

#define DISPLAY_POKE(addr,val) \
do { \
    vdpmemset(addr,val,1); \
} while(0)

#define DRAW(x,y,__tile,__color) \
do \
{ \
    DISPLAY_POKE(loc(x,y), (__tile)+(__color)); \
} \
while(0)

int main(void)
{
    uint8_t i;
    set_graphics(VDP_SPR_16x16);                        // set video mode
    charsetlc();                                        // load character set with lowercase
    vdpmemset(gImage, 32, 768);                         // clear screen
    VDP_SET_REGISTER(VDP_REG_COL, COLOR_BLACK);         // set screen color
    for(i=0;i<NUMBER_OF_STRINGS;++i)
    {
        DRAW(0,11+2*i, images[NUMBER_OF_STRINGS-i], COLOR_WHITE);
        PRINT(12,11+i*2, "HELLO" );
        PRINT(0,0,"");
    }
    while(1){};
    return 0;
}
```

loc.c

```
#include <conio.h>
#include <vdp.h>
#define uint8_t unsigned char
#define uint16_t unsigned int

uint16_t loc(uint8_t x, uint8_t y)
{
    return ((uint16_t) gImage)+(1)*x+(uint8_t)((1)*y)*((uint16_t) ((XSize) + 0));
}
```

I have also attached the EA5 file that shows the issue:

[X991.zip](https://github.com/user-attachments/files/17347907/X991.zip)

[loc.zip](https://github.com/user-attachments/files/17347851/loc.zip)

**Comment by mburkley** [comment]
Root cause was an attempt to negate a label in the rsubihi insn.  Fixed in 1.32
